
baseURL = "https://ringzzle.com/"
languageCode = "en-us"
title = "Ringzzle"
theme = "ananke"

enableRobotsTXT = true
buildFuture = false

[pagination]
pagerSize = 10

[params]
  mainSections = ["posts"]
